### PR TITLE
2.3

### PR DESCRIPTION
**Pull request by oilytin**
files moved and created to make it compatible with openTX 2.3.
All new files tested working on jumper t lite
no files deleted so there may be some redundant ones.
new files created with https://glados.c-net.org/ and converted with audacity

### CODE REVIEW

**Comment by jarethmt** [comment]
I'm not opposed to merging this, but a few questions first...
There are a lot of files that look touched in this pull request, not just new files added. I'm showing all the base numbers as being modified, can you explain why?
Also, regarding the README, it looks like you stripped out the majority of the setup / installation instructions I had. Can't merge this without the original README being intact.
Can you also please give some info in the README as to how to use the script that you set up?
If we can handle all these things I'd be happy to get this merged into master.

**Comment by oilytin** [comment]
Hi,
I had originally gone in with the intention of just adding the missing phrases but i started to notice a difference between your implementation of glados vs the https://glados.c-net.org/ one. 
So I went ahead and replaced all of the system sounds whilst bringing them up to date with otx2.3.
I also re sampled the game clips and normalised the volume of all the clips.
Great work btw i have been using it for a number of years now! Just started getting frustrated with the constant changes in otx.
I will have a look at the script and try to put a readme together, I am no coder and from what i remember it's a bit rough round the edges.

**Comment by jarethmt** [comment]
So, I thought I had documented this in the README, but apparently not.... So what I did is I used the "say" command in terminal on Mac OSX in order to generate all of the base sounds. I *think* I used the "Samantha" voice but I can't remember for sure, it's been years. I made a basic script that essentially looped over the say command for all of the numbers (1 - whatever the top is), and wrote the output to an appropriately named file. Then, I took all of those custom files and piped them through Melodyne to get the end result. Something like this video:

https://www.youtube.com/watch?v=1oQn66gvwKA

Not the most graceful, but it worked at the time and only took me an hour or two to put together while watching a movie. I'm pretty sure I did it this way because that service you used wasn't working as well at the time. It looks like they actually gave it an overhaul not too long ago.

So is your script essentially looping over all of those numbers and generating them using the web service instead?

Glad to hear you've gotten good use out of it :) I don't fly as much as I used to but it's still the pack on my transmitter and I smile a bit every time I hear it boot up.

Regarding the README, just copy over the OG readme. If there are any special notes you need to add you can, but try not to remove anything. Also, feel free to add a "contributors" section at the bottom with your github profile if you'd like.

**Comment by oilytin** [comment]
original readme reinstated with 2.3 update details added. the generate.sh file has a bit of info in the comments of that file so was going to leave as is.

**Comment by jarethmt** [comment]
Looks great to me, sorry it took so long to get this merged, just approved!

**Pull request merged**
